### ISSUE TITLE
cab uninstall deletes all MinGW libraries

### ISSUE THREAD

**Issue by RyanGlScott** [kazu-yamamoto/cab#33]
I uninstalled `cairo` on Windows one day using `cab`, then to my horror, I discovered sometime later that I no longer had any library files in my MSYS2 installation! It turns out that `cab` was responsible:

```
$ cab uninstall cairo -r
Deleting cairo 0.13.1.0
Deleting C:\Users\ryanscot\AppData\Roaming\cabal\x86_64-windows-ghc-7.10.2\cairo-0.13.1.0-BvHflyquX9N2z5gGhce0bJ
Deleting C:/msys64/mingw64/lib
Deleting C:\Users\ryanscot\AppData\Roaming\cabal\doc\x86_64-windows-ghc-7.10.2\cairo-0.13.1.0
```

It appears that [`getDirs`](https://github.com/kazu-yamamoto/cab/blob/ec780449da78d7c47edb8d502f3924bcfe5aaa3d/Distribution/Cab/Commands.hs#L127) is to blame, since it retrieves _all_ library directories that `ghc-pkg` discovers (including `C:/msys64/mingw64/lib`, which I definitely do _not_ want to be deleted!), and proceeds to delete them all.

Here was the output of `ghc-pkg field cairo library-dirs` prior to calling `cab uninstall`:

```
$ ghc-pkg field cairo library-dirs
library-dirs: C:\Users\ryanscot\AppData\Roaming\cabal\x86_64-windows-ghc-7.10.2\cairo-0.13.1.0-BvHflyquX9N2z5gGhce0bJ
              C:/msys64/mingw64/lib
```

**Comment by RyanGlScott** [comment]
Really, this isn't a Windows-specific issue. This would affect any Haskell library that was installed using the `--extra-lib-dirs` or `--extra-include-dirs` flags. This is probably an unintended consequence of #13.

**Comment by RyanGlScott** [comment]
Or maybe it _is_ a Windows-specific issue, since `cairo`'s `library-dirs` field on Linux doesn't contain the location where the `.so` files for `libcairo` are located (`/usr/lib/x86_64-linux-gnu`):

```
$ ghc-pkg field cairo library-dirs
library-dirs: /home/ryanscot/.cabal/lib/x86_64-linux-ghc-7.10.2/cairo-0.13.1.0-BvHflyquX9N2z5gGhce0bJ
```

**Comment by RyanGlScott** [comment]
OK, I see why I never encountered this issue on Linux. It has to do with how each OS _discovers_ the library paths.

On Linux, the shared object files are located in a standard location that the OS knows (via `LIBRARY_PATH` or other means), so `cabal-install` never has to explicitly add them with the `--extra-library-dirs`. One can replicate this behavior on Windows by manually setting the `LIBRARY_DIRS` flag prior to installing a package. For example, using a `pcre-light` sandbox:

```bash
ryanscot@ryanscot-MOBL MINGW64 .../Hacking/Haskell/pcre-light-0.4.0.3
$ pkg-config --libs libpcre
-LC:/msys64/mingw64/lib -lpcre

ryanscot@ryanscot-MOBL MINGW64 .../Hacking/Haskell/pcre-light-0.4.0.3
$ pkg-config --cflags libpcre
-IC:/msys64/mingw64/include

ryanscot@ryanscot-MOBL MINGW64 .../Hacking/Haskell/pcre-light-0.4.0.3
$ export C_INCLUDE_PATH="C:/msys64/mingw64/include"

ryanscot@ryanscot-MOBL MINGW64 .../Hacking/Haskell/pcre-light-0.4.0.3
$ export LIBRARY_PATH="C:/msys64/mingw64/lib"

ryanscot@ryanscot-MOBL MINGW64 .../Hacking/Haskell/pcre-light-0.4.0.3
$ cabal install -j1
...

ryanscot@ryanscot-MOBL MINGW64 .../Hacking/Haskell/pcre-light-0.4.0.3
$ cabal exec ghc-pkg field pcre-light library-dirs
library-dirs: C:\Users\ryanscot\Documents\Hacking\Haskell\pcre-light-0.4.0.3\.cabal-sandbox\x86_64-windows-ghc-7.10.2\pcre-light-0.4.0.3-J9bYKMfE86x9lEV1P3lTdK
```

Now, `library-dirs` doesn't contain `C:/msys64/mingw64/lib`, so `cab uninstall` shouldn't delete it. Sure enough:

```bash
ryanscot@ryanscot-MOBL MINGW64 .../Hacking/Haskell/pcre-light-0.4.0.3
$ cab uninstall pcre-light -r
Deleting pcre-light 0.4.0.3
Deleting C:\Users\ryanscot\Documents\Hacking\Haskell\pcre-light-0.4.0.3\.cabal-sandbox\x86_64-windows-ghc-7.10.2\pcre-light-0.4.0.3-J9bYKMfE86x9lEV1P3lTdK
Deleting C:\Users\ryanscot\Documents\Hacking\Haskell\pcre-light-0.4.0.3\.cabal-sandbox\doc\x86_64-windows-ghc-7.10.2\pcre-light-0.4.0.3
```

Of course, it would probably be best if we could just avoid deleting directories like `C:/msys64/mingw64/lib` altogether if they happen to be in `library-dirs`.

One idea: we only delete `library-dirs` that have certain prefix(es). In the above example, it looks like those prefixes would be `C:\Users\ryanscot\Documents\Hacking\Haskell\pcre-light-0.4.0.3\.cabal-sandbox\x86_64-windows-ghc-7.10.2\pcre-light-0.4.0.3-J9bYKMfE86x9lEV1P3lTdK` and `C:\Users\ryanscot\Documents\Hacking\Haskell\pcre-light-0.4.0.3\.cabal-sandbox\doc\x86_64-windows-ghc-7.10.2\pcre-light-0.4.0.3` (which both have `C:\Users\ryanscot\Documents\Hacking\Haskell\pcre-light-0.4.0.3\.cabal-sandbox\doc\x86_64-windows-ghc-7.10.2\pcre-light-0.4.0.3` as a common prefix, but I'm not sure if that's _always_ the case).

@kazu-yamamoto, can you think of an example where that wouldn't work? If not, I could make a pull request for this.

**Comment by kazu-yamamoto** [comment]
Sorry for the delay. Please make a pull request. I would love to merge it.
